#!/bin/bash

[ $# -lt 1 ] && display_help=true

while [[ $# -gt 0 ]]
do
    key="$1"

    case $key in
        -u|--udp)
            use_udp=true
            ;;
        -h|--help)
            display_help=true
            ;;
        -c|--connect)
            connect_to_specific=true
            shift
            REMOTE_PEER_ADDRESS=$1
            ;;
        *)
            REF=$key
        ;;
    esac
    shift
done

[ "$display_help" = true -o -z "$REF" ] && echo "Usage: $0 [--udp] [--connect <address>] <data ref>" && exit

set -em

[ -z $IPFS_BIN ] && IPFS_BIN=ipfs

# Initialize the repo
export IPFS_PATH=$(pwd)/ipfs_receive
mkdir -p $IPFS_PATH
$IPFS_BIN init

# Modify the swarm addresses in case udp should be used
if [ "$use_udp" = true ] ; then
    $IPFS_BIN config --json Addresses.Swarm \
        '["/ip4/0.0.0.0/udp/4001/utp", "/ip6/::/udp/4001/utp"]'
fi

# Start the daemon
set -m
$IPFS_BIN daemon &
IPFS_PID=$!

trap "trap - SIGINT SIGTERM EXIT; \
      kill $IPFS_PID; \
      wait $IPFS_PID; \
      exit" SIGINT SIGTERM EXIT

# Wait for daemon to start
sleep 0.2
until $IPFS_BIN swarm peers >/dev/null 2>&1; do
	echo -n .
	sleep 0.2
done

# If needed to connect to specific peer
if [ "connect_to_specific" = true ] ; then
    $IPFS_BIN swarm connect $REMOTE_PEER_ADDRESS
fi

# Move to data directory
mkdir -p data
cd data
rm -f ipfs.rrd

# Start data collection
./ipfs-benchmark/ipfs-collect data &

trap "trap - SIGINT SIGTERM EXIT; \
      kill $IPFS_PID; \
      killall ipfs-collect; \
      wait $IPFS_PID; \
      rm -r $IPFS_PATH; \
      exit" SIGINT SIGTERM EXIT

# Download test data
$IPFS_BIN get -o data $REF
sleep 3

# Clean up
killall ipfs-collect
kill $IPFS_PID
trap - SIGINT SIGTERM EXIT
wait $IPFS_PID
rm -r $IPFS_PATH

# Show results
../ipfs-benchmark/ipfs-graph
feh ipfs.png
