#!/bin/sh

[ $# -ne 1 ] && echo -e "Usage: $0 <size in megabytes>" && exit

DATA_SIZE=$1 # megabytes

set -em

[ -z $IPFS_BIN ] && IPFS_BIN=ipfs

# Initialize the repo
export IPFS_PATH=ipfs_send
mkdir -p $IPFS_PATH
$IPFS_BIN init

# Modify ports to allow two ipfs instances on the same host
$IPFS_BIN config --json Addresses \
'{
   "Swarm": [ "/ip4/0.0.0.0/tcp/4002", "/ip6/::/tcp/4002" ],
   "API": "/ip4/127.0.0.1/tcp/5002",
   "Gateway": "/ip4/127.0.0.1/tcp/8082"
}'

# Start the daemon
$IPFS_BIN daemon &
IPFS_PID=$!

trap "trap - SIGINT SIGTERM EXIT; \
      kill $IPFS_PID; \
      wait $IPFS_PID; \
      exit" SIGINT SIGTERM EXIT

# Wait for daemon to start
sleep 0.5
until $IPFS_BIN swarm peers >/dev/null 2>&1; do
	echo -n .
	sleep 0.5
done

# Make test data
echo "Generating test data..."
ref=$(dd if=/dev/urandom iflag=fullblock bs=1M count=$DATA_SIZE \
      | $IPFS_BIN add -q)

# Wait for signal
echo "Sender started with $ref"
echo "Press ctrl-C to stop"

trap "trap - SIGINT SIGTERM EXIT; \
      kill $IPFS_PID; \
      wait $IPFS_PID;
      rm -r $IPFS_PATH" SIGINT SIGTERM EXIT
wait $IPFS_PID
